### ISSUE TITLE
Add a list of good places for new contributors to go

### ISSUE THREAD

**Issue by Frijol** [tessel/onboarding#9]
e.g. docs, anywhere with a contribution-easy or help-wanted tag

**Comment by tcr** [comment]
- https://github.com/tessel/project/issues/102

**Comment by tcr** [comment]
- https://github.com/tessel/t2-cli/labels/contribution-easy

**Comment by Frijol** [comment]
- https://github.com/tessel/t2-docs/issues/14
- https://github.com/tessel/t2-start/issues

**Comment by Frijol** [comment]
should be covered if https://github.com/tessel/project/issues/152 gets fully implemented, closing this issue in favor of that one
